PackingRaport/ViewModels/RaportViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using PackingRaport.Domain.Models;

namespace PackingRaport.ViewModels
{
    public class RaportViewModel
    {
        public int Id { get; set; }
        public DayOfWeek Day { get; set; }
        public DateTime StartProductionTime { get; set; }
        public DateTime? EndProductionTime { get; set; }
        public int Quantity { get; set; }
        public string Comments { get; set; }

    }
}

PackingRaport/Controllers/RaportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PackingRaport.Domain.InterfaceRepository;
using PackingRaport.Domain.Models;
using System.Security.Claims;
using AutoMapper;
using PackingRaport.Helpers;
using PackingRaport.Persistance.Context;
using PackingRaport.Services.Interfaces;
using PackingRaport.ViewModels;

namespace PackingRaport.Controllers
{
    public class RaportController : Controller
    {
        private readonly IRaportRepositories _raportRepositories;
        private readonly IUserRepository _userRepository;
        private readonly IRaportServices _raportServices;
        private readonly IMapper _mapper;

        PackingRaportHelpers _helpers = new PackingRaportHelpers();
        public RaportController(IRaportRepositories raportRepositories, IUserRepository userRepository,
            IRaportServices raportServices, RaportDbContext dbContext, IMapper mapper)
        {
            _raportRepositories = raportRepositories;
            _userRepository = userRepository;
            _raportServices = raportServices;
            _mapper = mapper;
        }

        [HttpGet]
        public ViewResult Index(string? sortOrder, string searchString, DateTime? searchDate, TypeProduct? searchType)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            var raports = _raportRepositories.GetAllRaports();

            if (!String.IsNullOrEmpty(searchString))
            {
                raports = raports.Where(s => s.User.Name.Contains(searchString)
                                             || s.User.Surname.Contains(searchString));
            }

            if (searchDate.HasValue)
            {
                raports = raports.Where(s => s.StartProductionTime.Date == searchDate.Value.Date);
            }

            if (searchType.HasValue)
            {
                raports = raports.Where(s => s.Product.ProductName == searchType.Value);
            }

            switch (sortOrder)
            {
                case "name_desc":
                    raports = raports.OrderByDescending(s => s.StartProductionTime);
                    break;
                case "Date":
                    raports = raports.OrderBy(s => s.Containers.Type);
                    break;
                case "date_desc":
                    raports = raports.OrderByDescending(s => s.Product.ProductName);
                    break;
                default:
                    raports = raports.OrderBy(s => s.User.Surname);
                    break;
            }

            return View(raports.ToList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var listUsers = _userRepository.GetAllUsers();

            List<SelectListItem> userListName = new List<SelectListItem>();

            User user = _userRepository.GetUserById(id);

            userListName.Add(new SelectListItem(user.Name + " " + user.Surname, user.Id));

            ViewBag.UserListName = userListName;

            ViewBag.ProductList = Enum.GetValues(typeof(TypeProduct)).Cast<TypeProduct>().Select(p => new SelectListItem
            {
                Text = p.ToString(),
                Value = p.ToString()
            }).ToList();

            ViewBag.ContainerList = Enum.GetValues(typeof(TypeContainer)).Cast<TypeContainer>().Select(c => new SelectListItem
            {
                Text = c.ToString(),
                Value = ((int)c).ToString()
            }).ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateConfirmed(Raport raport)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _userRepository.GetUserById(userId);

            if (user == null)
            {
                return NotFound();
            }

            _raportRepositories.AddRaport(_raportServices.CreateRaport(raport, user));

            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var result = _raportRepositories.GetById(id);

            ViewBag.UserName = _raportServices.GetUser(id);
            ViewBag.ProductName = _raportServices.GetProduct(id);
            ViewBag.Container = _raportServices.GetContainers(id);

            return View(result);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var raport = _raportRepositories.GetById(id);

            RaportViewModel raportViewModel = _mapper.Map<RaportViewModel>(raport);

            return View(raportViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var raport = _raportRepositories.GetById(id);

            if (raport == null)
            {
                return NotFound();
            }

            _raportRepositories.RemoveRaport(raport);

            return RedirectToAction("Index");
        }


        public IActionResult Edit(int id)
        {
            var result = _raportRepositories.GetById(id);

            

            ViewBag.UserName = _raportServices.GetUser(id);
            //ViewBag.ProductList = new SelectList(result.);
            //ViewBag.Container = _raportServices.GetContainers(id);

            ViewBag.ProductList = Enum.GetValues(typeof(TypeProduct)).Cast<TypeProduct>().Select(x => new SelectListItem
            {
                Text = x.ToString(),
                Value = x.ToString(),
                Selected = result.Product.ProductName == x
            })
            .ToList();

            ViewBag.ContainerList = Enum.GetValues(typeof(TypeContainer)).Cast<TypeContainer>().Select(c => new SelectListItem
            {
                Text = c.ToString(),
                Value = ((int)c).ToString()
            }).ToList();


            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditConfirmed(Raport raport, int id)
        {
            var existingRaport = _raportRepositories.GetById(id);

            existingRaport.Day = raport.Day;
            existingRaport.StartProductionTime = raport.StartProductionTime;
            existingRaport.EndProductionTime = raport.EndProductionTime;
            existingRaport.Quantity = raport.Quantity;
            existingRaport.Product = raport.Product;
            existingRaport.Containers = raport.Containers;
            existingRaport.Comments = raport.Comments;

            _raportRepositories.Update(existingRaport);

            return RedirectToAction("Index");
        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult EditConfirmed(Raport raport, int id)
        //{
        //    //var result = _raportRepositories.GetById(raport.Id);

        //    ViewBag.UserName = _raportServices.GetUser(id);
        //    ViewBag.ProductName = _raportServices.GetProduct(id);
        //    ViewBag.Container = _raportServices.GetContainers(id);

        //    //_raportServices.UpdateRaport(result);

        //    _raportServices.UpdateRaport(raport);

        //    return RedirectToAction("Index");

        //    return RedirectToAction("Index");
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult EditConfirmed(int? id)
        //{

        //}
    }
}

PackingRaport/Views/Raport/Create.cshtml
@using PackingRaport.Domain.Models
@model PackingRaport.Domain.Models.Raport

@{
    ViewData["Title"] = "Create";
}

@*<div class="container">

</div>*@

<h4 class="text-center">Raport</h4>
<hr />
<div class="row justify-content-center align-items-center">
    <div class="col-md-4 text-center">
        <form asp-action="CreateConfirmed">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="day">Dzień tygodnia:</label>
                <select id="day" name="day" class="form-control">
                    <option value="1">Poniedziałek</option>
                    <option value="2">Wtorek</option>
                    <option value="3">Środa</option>
                    <option value="4">Czwartek</option>
                    <option value="5">Piątek</option>
                    <option value="6">Sobota</option>
                    <option value="0">Niedziela</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="User.Name"></label>
                <select asp-for="User.Name" class="form-control" asp-items="ViewBag.UserListName">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="StartProductionTime"></label>
                <input asp-for="StartProductionTime" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="EndProductionTime"></label>
                <input asp-for="EndProductionTime" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Product.ProductName" class="control-label"></label><br />
                <select style="width: 100%" asp-for="Product.ProductName" asp-items="ViewBag.ProductList"></select>
            </div>
            <div class="form-group">
                <label asp-for="Containers.Type" class="control-label"></label><br />
                <select style="width: 100%" asp-for="Containers.Type" asp-items="ViewBag.ContainerList"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Comments"></label>
                <textarea asp-for="Comments" class="form-control" style="height: 150px;"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary mt-3" />
                <input type="button" value="Powrót do listy" class="btn btn-primary mt-3" onclick="location.href='@Url.Action("Index", "Raport" )'" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
}

PackingRaport/Views/Raport/Delete.cshtml
@model PackingRaport.ViewModels.RaportViewModel;

@{
    ViewData["Title"] = $"Delete user";
}

<h2>Delete @Model.</h2>

<p>Czy napewno chcesz usunąć raport o numerze @Model.Id?</p>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartProductionTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartProductionTime)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndProductionTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndProductionTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed">
        <input type="hidden" value="@Model.Id" name="Id" />
        <input type="submit" value="Delete" class="btn btn-outline-secondary btn-sm align-text-bottom" />
        <input type="button" value="Back to List" class="btn btn-outline-secondary btn-sm align-text-bottom" onclick="location.href='@Url.Action("Index", "Raport" )'" />

    </form>
</div>

PackingRaport/Views/Raport/Details.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model PackingRaport.Domain.Models.Raport
@using Microsoft.AspNetCore.Mvc.Rendering
@using PackingRaport.Domain


@{
    ViewData["Title"] = "Details";
}

<h3>Szczegóły</h3>

<div>
    <hr />
    <dl class="row">
       @* <div class ="col-md-4">
            <dt>
                <label>Id</label>
            </dt>
            <dd>
                @Model.Id
            </dd>
        </div>*@
        <div class="col-md-2">
            <dt>
                <label>Operator</label>
            </dt>
            <dd>
                @ViewBag.UserName
            </dd>
        </div>
        <div class="col-md-2">
            <dt>
                <label>Start</label>
            </dt>
            <dd>
                @Model.StartProductionTime
            </dd>
        </div>
        <div class="col-md-2">
            <dt>
                <label>Koniec</label>
            </dt>
            <dd>
                @Model.EndProductionTime
            </dd>
        </div>
        <div class="col-md-2">
            <dt>
                <label>Produkt</label>
            </dt>
            <dd>
                @ViewBag.ProductName
            </dd>
        </div>
        <div class="col-md-2">
            <dt>
                <label>Zbiornik</label>
            </dt>
            <dd>
                @ViewBag.Container
            </dd>
        </div>
        <div class="col-md-2">
            <dt>
                <label>Ilość</label>
            </dt>
            <dd>
                @Model.Quantity
            </dd>
        </div>
        <div class="col-md-4">
            <dt>
                <label>Uwagi</label>
            </dt>
            <dd>
                @Model.Comments
            </dd>
        </div>



       @* <dt class="col-md-4">
            <label>Operator:</label>
        </dt>
        <dd class="col-md-4">
            @ViewBag.UserName
        </dd>
       <dt class="col-md-4">
            <label>Produkt:</label>
        </dt>
        <dd class="col-md-4">
            @ViewBag.ProductName
        </dd>
        <dt class="col-md-4">
            <label>Start:</label>
        </dt>
        <dd class="col-md-4">
            @Model.StartProductionTime
        </dd>
        <dt class="col-md-4">
            <label> Zbiornik:</label>
        </dt>
        <dd class="col-md-4">
            @ViewBag.Container
        </dd>
        <dt class="col-md-4">
            <label>Koniec:</label>
        </dt>
        <dd class="col-md-4">
            @Model.EndProductionTime
        </dd>
        <dt class="col-md-4">
            <label>Uwagi:</label>
        </dt>
        <dd class="col-md-4">
            @Model.Comments
        </dd>
        <dt class="col-md-4">
            <label>Ilość:</label>
        </dt>
        <dd class="col-md-4">
            @Model.Quantity
        </dd>
*@
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PackingRaport/Views/Raport/Edit.cshtml
@model PackingRaport.Domain.Models.Raport;


@{
    ViewData["Title"] = "Edit";
}

<h1>Edycja</h1>

<h4 class="text-center">Raport</h4>
<hr />
<div class="row justify-content-center align-items-center">
    <div class="col-md-4 text-center">
        <form asp-action="EditConfirmed">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="day">Dzień tygodnia:</label>
                <select id="day" name="day" class="form-control">
                    <option value="1">Poniedziałek</option>
                    <option value="2">Wtorek</option>
                    <option value="3">Środa</option>
                    <option value="4">Czwartek</option>
                    <option value="5">Piątek</option>
                    <option value="6">Sobota</option>
                    <option value="0">Niedziela</option>
                </select>
            </div>
            <div class="form-group">
                <label for="username">Nazwa użytkownika:</label>
                <input type="text" id="username" class="form-control" value="@ViewBag.UserName" readonly />
            </div>
            <div class="form-group">
                <label asp-for="StartProductionTime"></label>
                <input asp-for="StartProductionTime" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="EndProductionTime"></label>
                <input asp-for="EndProductionTime" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Product.ProductName" class="control-label"></label><br />
                <select style="width: 100%" asp-for="Product.ProductName" asp-items="ViewBag.ProductList"></select>
            </div>
            <div class="form-group">
                <label asp-for="Containers.Type" class="control-label"></label><br />
                <select style="width: 100%" asp-for="Containers.Type" asp-items="ViewBag.ContainerList"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Comments"></label>
                <textarea asp-for="Comments" class="form-control" style="height: 150px;"></textarea>
            </div>
            <div class="form-group">

                <input type="submit" value="Dodaj" class="btn btn-primary mt-3" />
                <input type="button" value="Powrót do listy" class="btn btn-primary mt-3" onclick="location.href='@Url.Action("Index", "Raport" )'" />
            </div>
        </form>
    </div>
</div>


<div>
    @*<a asp-action="Index">Back to List</a>*@
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PackingRaport/Views/Raport/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<PackingRaport.Domain.Models.Raport>
@using Microsoft.AspNetCore.Mvc.Rendering
@using PackingRaport.Domain.Models


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Raport</h3>

@*<p>Data: @DateTime.Now.ToString("yyyy-MM-dd")</p>

<p>
    <a asp-action="Create">Dodaj nowy produkcję</a>
</p>*@

@*<div class="row">
    <div class="col-2">
        <p>Data: @DateTime.Now.ToString("yyyy-MM-dd")</p>
    </div>
    <div class="col-2">
        <a asp-action="Create" class="btn btn-light">Dodaj nowy produkcję</a>
    </div>
</div>*@
<p class="d-inline-block">Data: @DateTime.Now.ToString("yyyy-MM-dd")</p>

<div class="d-flex justify-content-between">
    <form method="get">
        <p>
            Find by: <input type="date" name="searchDate" />

            <select name="searchType">
                <option value="">--Wybierz produkt--</option>
                @foreach (var item in Enum.GetValues(typeof(TypeProduct)))
                {
                    <option value="@item">@item</option>
                }
            </select>

            <input type="submit" value="Filter" />
        </p>
    </form>
    <p class="d-inline-block p-2">
        <a asp-action="Create" class="btn btn-secondary">Dodaj nową produkcję</a>
    </p>
</div>

<table class="table  table-bordered">
    <thead class="thead-light">
        <tr>
            @*<th>Id</th>*@
            <th scope="col">Dzień tygodnia</th>
            <th scope="col">Imie</th>
            <th scope="col">Nazwisko</th>
            <th scope="col">Produkt</th>
            <th scope="col">Start Produkcji</th>
            <th scope="col">Koniec Produkcji</th>
            <th scope="col">Zbiornik</th>
            <th scope="col">Ilość</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var raport in Model)
        {
            <tr>
                @*<td>@raport.Id</td>*@
                <td>@raport.Day.ToString()</td>
                <td>@raport.User.Name</td>
                <td>@raport.User.Surname</td>
                <td>@raport.Product.ProductName</td>
                <td>@raport.StartProductionTime.ToString("dd.MM.yyyy")</td>
                <td>@raport.EndProductionTime</td>
                <td>@raport.Containers.Type</td>
                <td>@raport.Quantity</td>

                <td class="d-flex justify-content-center">
                    <input type="button" value="Szczegóły" class="btn btn-outline-secondary btn-sm align-text-bottom mx-1" onclick="location.href='@Url.Action("Details", "Raport",new { Id = raport.Id } )'" />
                    <input type="button" value="Usuń" class="btn btn-outline-secondary btn-sm align-text-bottom mx-1" onclick="location.href='@Url.Action("Delete", "Raport",new { Id = raport.Id } )'" />
                    <input type="button" value="Edytuj" class="btn btn-outline-secondary btn-sm align-text-bottom mx-1" onclick="location.href='@Url.Action("Edit", "Raport",new { Id = raport.Id } )'" />
                </td>

          @*      <td class="d-flex justify-content-center ">

                    <input type="button" value="Szczegóły" class="btn btn-outline-secondary btn-sm align-text-bottom" onclick="location.href='@Url.Action("Details", "Raport",new { Id = raport.Id } )'" />
                    <input type="button" value="Usuń" class="btn btn-outline-secondary btn-sm align-text-bottom" onclick="location.href='@Url.Action("Delete", "Raport",new { Id = raport.Id } )'" />


                    <input class="mx-2" type="submit" value="Popraw" asp-action="Edit" asp-controller="Raport" />
                    <input class="mx-2" type="submit" value="Szczegóły" asp-action="Details" asp-route-id="@raport.Id" asp-controller="Raport" />
                    <input class="mx-2" type="submit" value="Usuń" asp-action="Delete" asp-controller="Raport" />*@
                    @*<a asp-action="Edit" asp-route-id="@raport.Id">Popraw</a> |
                <a asp-action="Details" asp-route-id="@raport.Id">Szczegóły</a> |
                <a asp-action="Delete" asp-route-id="@raport.Id">Usuń</a>
                </td>*@
            </tr>
        }
    </tbody>
</table>